version: '3.8'

services:
  consul-bank-abc:
    image: hashicorp/consul:latest
    container_name: consul-bank-abc
    restart: always
    ports:
      - "8500:8500"   # Consul UI and API
      - "8600:8600/udp" # DNS Interface
    networks:
      - kong-net
    volumes:
      - consul-data:/consul/data
    command: agent -server -bootstrap -node=consul-bank-abc -client=0.0.0.0 -ui -bind=0.0.0.0
    environment:
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'

networks:
  kong-net:
    external: true

volumes:
  consul-data:
