services:
  mysql:
    image: mysql:8.0
    container_name: mysql_security
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: security_token
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kong-net

volumes:
  mysql_data:
    driver: local

networks:
  kong-net:
    external: true