services:
  product-app:
    image: quarkus/ms-quarkus-product-api-jvm:latest
    container_name: ms-quarkus-product-api
    environment:
      - POSTGRES_URL=jdbc:postgresql://product-database-postgres:5432/product_db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=admin
      - SERVICE_ADDRESS_CONSUL=consul-bank-abc
      - SERVICE_ADDRESS_NAME=ms-quarkus-product-api
    ports:
      - "8081:8081"
    networks:
      - kong-net

networks:
  kong-net:
    external: true