GET http://localhost:8082/api/v1/customers

GET http://localhost:8082/api/v1/customer/3

#find products for fill as client product using vertx client, find by customer id
GET http://localhost:8082/api/v1/customer/1/product

#find products for fill as client product using stork client, find by customer id
#GET http://localhost:8082/api/v1/customer/findById/1

#find products for fill as client product using stork client, find by customer id
GET http://localhost:8082/api/v1//customer/findProductFillByCustomerId/1

