GET http://localhost:8001/services
GET http://localhost:8001/routes

#delete routes
DELETE http://localhost:8001/routes/40ed1368-1117-49b4-8566-558cd0364984
DELETE http://localhost:8001/routes/get-token-route
#delete services
DELETE http://localhost:8001/services/ffba4bf1-73e2-4f50-88c7-d37423e5b0e8
DELETE http://localhost:8001/services/get-token


#admin
GET http://localhost:8084/api/v1/user/ADMIN

POST http://localhost:8084/api/v1/admin/login
Content-Type:application/json
{
  "username": "ADMIN",
  "password": "admin123"
}

#client
GET http://localhost:8084/api/v1/user/VENDOR

POST http://localhost:8001/services
Content-Type:application/json
{
	"name": "get-users",
	"protocol": "http",
	"host": "ms-quarkus-security-api",
	"port": 8084,
	"path": "/api/v1/users",
	"tags": ["user-service", "security-api"]
}

#route get users to service
POST http://localhost:8001/services/get-users/routes
Content-Type:application/json
{
	"name": "get-users-route",
	"paths": [
		"/api/v1/users"
	],
	"methods": [
		"GET",
		"POST"
	]
}

#find by username
POST http://localhost:8001/services
Content-Type:application/json
{
	"name": "get-username",
	"protocol": "http",
	"host": "ms-quarkus-security-api",
	"port": 8084,
	"path": "/api/v1/user",
	"tags": ["user-service", "security-api"]
}

#route get users to service
POST http://localhost:8001/services/get-username/routes
Content-Type:application/json
{
	"name": "get-username-route",
	"paths": [
		"/api/v1/user"
	],
	"methods": [
		"GET"
	]
}

#find by username
POST http://localhost:8001/services
Content-Type:application/json
{
	"name": "get-token",
	"protocol": "http",
	"host": "ms-quarkus-security-api",
	"port": 8084,
	"path": "/api/v1/admin/login",
	"tags": ["user-service", "security-api"]
}

#route get users to service
POST http://localhost:8001/services/get-token/routes
Content-Type:application/json
{
	"name": "get-token-route",
	"paths": [
		"/api/v1/admin/login"
	],
	"methods": [
		"POST"
	]
}