services:
  product-database-postgres:
    image: postgres:14-alpine
    container_name: product-database-postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=product_db
    networks:
      - kong-net

volumes:
  postgres_data:
    name: product_postgres_data

networks:
  kong-net:
    external: true