services:
  customer-database-postgres:
    image: postgres:14-alpine
    container_name: customer-database-postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=customer_db
    networks:
      - kong-net

  customer-app:
    image: quarkus/ms-quarkus-customer-api-jvm:latest
    container_name: ms-quarkus-customer-api
    depends_on:
      - customer-database-postgres
    environment:
      - POSTGRES_URL=postgresql://customer-database-postgres:5432/customer_db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=admin
      - CLIENT_HOST_PRODUCT=http://ms-quarkus-product-api
      - CLIENT_HOST_PRODUCT_GQL=http://ms-quarkus-product-api:8081/graphql
    ports:
      - "8082:8082"
    networks:
      - kong-net

networks:
  kong-net:
    external: true

volumes:
  postgres_data:
    name: customer_postgres_data