GET http://localhost:8083/api/v1/products
accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3F1YXJrdXMuaW8vaXNzdWVyIiwidXBuIjoiVkVORE9SIiwiZ3JvdXBzIjpbIkNVU1RPTUVSIl0sImlhdCI6MTczOTg1NTM2MiwiZXhwIjoxNzM5ODU4OTYyLCJqdGkiOiIwYTVmMGUzNy0wZjkyLTQ5ZDktODQ1NC0yN2Q3OTMyNzRhZTUifQ.Guh9db6XyUnfQZy1FCMfLRt30sECT2jB1rbW9xp1ls6kT2RfuVKOvWTpnCXQuv3MPcSIZhQTKmINsh_A_nY5cdKHLuvZliv_9TCa61I2mNbuTEPMqqX8SQMHEymtUzn1BmnWG3bjGppjiWXgD-rJ89U-lDEgFQfaWdZYtMv-Y8BN0KJnUzyYYwdWHaHR0PbSTwz4OSYX-6W7kPXXo3C96wZR_WkZ1ME_u2jxQjOMcM1gqKuKMxlzkE5iNlptNy9GeQcFxDISX_qC1V7ItiPHvAdugDzDQxcKnZ09Vy6pJK9eCJTn-c2S7D5oWoHEaehU_6k6E7_k-4UbtohpjF93sw