services:
  postgres:
    image: postgres:13
    container_name: postgres-multi-db
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh  # Mount initialization script
    networks:
      - postgres-net

volumes:
  postgres_data:

networks:
  postgres-net:
    driver: bridge